version: '3'

services:
  postgres:
    environment:
        - POSTGRES_USER=root
        - POSTGRES_DB=postgres
        - POSTGRES_PASSWORD=postgres
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
#      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  web:
    build: .
    ports:
      - "8080:5000"